akanoren/redsky

static/css/style.css
・Postボタンを青にしました
・Refreshボタンを紫にしました
・投稿の文字サイズを17pxへと変更しました。
・投稿フォームを角丸にしました。
・投稿文字の位置やボタンのサイズなどを調整しました。
=> style.cssの作成

static/css/pointer.css, static/css/style.css
ボタンの上に合わせたとき、マウスカーソルを指マークにするだけの単純なCSSです。
=> ボタンのマウスホバー時、カーソルを指マークにする

static/css/pointer.css
pointer.cssはstyle.cssに統合されたので、削除しました。
=> pointer.cssの削除

src/lib/components/post.svelte, static/css/style.css
=> Add Avatar image

static/css/style.css
=> 線の色を#DDDDDDにした

static/css/style.css
ボタンの上下のpaddingをそれぞれ5pxから8pxにしました。
=> ボタンの上下のpaddingを8pxにした

static/css/style.css
=> ボタン用のアイコンが表示されるようにCSSを変更

static/css/style.css
セレクタをinput.submit-postに修正しました。
=> セレクタをinput.submit-postに修正

package-lock.json, package.json, src/app.html, src/lib/components/post.svelte, static/css/style.css
=> Add timestamp

static/css/style.css
Post用のアイコンをpost5.pngに、Refresh用のアイコンをrefresh2.pngに変更させるためにstyle.cssを書き換えました。
=> ボタン用のアイコンを変更するためにstyle.cssを書き換え

static/css/style.css
PostボタンとRefreshボタンのアイコンの位置を修正しました
=> PostボタンとRefreshボタンのアイコンの位置を修正

static/css/style.css
PostボタンとRefreshボタンとアイコンの位置を調整しました。
=> PostボタンとRefreshボタンとアイコンの位置を調整

static/css/style.css
=> レスポンシブデザイン対応

static/css/style.css
=> タブレットのレスポンシブデザインに対応

static/css/style.css
・iPhone SEに対応しました。
・タイムスタンプのフォントをArialにし、斜体（italic）にしました。
=> iPhone SEへの対応とタイムスタンプをフォントの変更

static/css/style.css
=> PC環境で横幅が広くなってしまう問題を修正

static/css/style.css
タイムラインの文字サイズを15pxから17pxに修正しました。
=> タイムラインの文字サイズを15pxから17pxに修正

static/css/style.css
=> スマホ環境でアカウント名と本文の位置を合わせた

static/css/style.css
スマホとパソコン環境でアカウント名と本文の位置を合わせました。
=> スマホとパソコン環境でアカウント名と本文の位置を合わせた

static/css/style.css
iPhone SE環境でのアカウント名と本文の位置を合わせました。
=> iPhone SE環境でのアカウント名と本文の位置を合わせた

static/css/style.css
=> フォントサイズを追加

static/css/style.css
=> 投稿フォームをpaddingで修正

static/css/style.css
・スマホ環境でスクロールしても投稿フォームとボタンの位置を固定化しました。
・Refreshボタンの位置を微修正しました。
=> スマホ環境でスクロールしても投稿フォームとボタンの位置を固定化

static/css/style.css
=> 投稿フォームの位置を微修正

static/css/style.css
=> スマホ環境でPostボタンの位置を少し左に移動した

src/manifest.json
=> manifest.jsonファイルの追加

src/app.html
=> manifest.jsonを参照可能にした

src/app.html
=> スマホ環境でピンチアウトを禁止

src/app.html
=> スマホ環境で拡大縮小出来ないように修正
